import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

const pageUrl = new URL("./page.tsx", import.meta.url)
const globalsUrl = new URL("../globals.css", import.meta.url)
const componentsUrl = new URL("../../features/assessment/components.tsx", import.meta.url)

test("assessment entry keeps the forced pause ritual", async () => {
  const page = await readFile(pageUrl, "utf8")
  const globals = await readFile(globalsUrl, "utf8")
  const components = await readFile(componentsUrl, "utf8")

  assert.ok(page.includes("回想最近一次"), "entry should open with the revised recent trading moment prompt")
  assert.ok(page.includes("你定好了计划,却没守住。"), "entry should focus on not keeping the planned action")
  assert.ok(page.includes("慢慢想"), "entry should ask the user to think slowly")
  assert.equal(page.includes("别急着回答"), false, "entry should no longer show the extra pause instruction")
  assert.ok(page.includes("<PrimaryButton type=\"button\" onClick={startAssessment} className=\"w-full\">"), "ready button should keep the locked pre-water entry")
  assert.ok(page.includes("照见此心"), "ready button copy should stay locked")
  assert.equal(page.includes(">入照心<"), false, "ready button should not keep the previous name")
  assert.ok(page.includes("只为省察此心，不为评判对错。"), "entry note before the water gateway should stay locked")
  assert.equal(page.includes("ritual-account-corner"), false, "account hint should not appear on the assessment entry ritual page")
  assert.equal(page.includes("尾号 {phoneTail}"), false, "phone tail should move to the home first-screen account chip")
  assert.equal(page.includes("ritual-account-dot"), false, "account dot should move to the home first-screen account chip")
  assert.equal(page.includes("你没有守住自己的交易瞬间。"), false, "entry should not keep the old prompt sentence")
  assert.equal(page.includes("你定好计划，却没有守住那一刻！"), false, "entry should not keep the previous longer wording")
  assert.equal(page.includes("你定好了计划，却没有守住那一刻！"), false, "entry should not keep the previous wording")
  assert.equal(page.includes("你定好了计划，却没守住。"), false, "entry should not use the Chinese comma version")
  assert.equal(page.includes("setIsEditingName"), false, "phone tail should no longer sit in an editable badge above the button")
  assert.ok(!page.includes("先别急着回答。"), "pause instruction should not lead before the prompt")
  assert.ok(!page.includes("选最像你的那个念头。"), "entry should not add an extra instruction line")
  assert.ok(page.includes("此心一照，妄念自明。"), "opening transition should keep the original seal copy")
  assert.ok(page.includes('<AssessmentShell background="home-water" contentWidth="wide">'), "reflect entry should reuse the home still-water background")
  assert.ok(components.includes('import { HomeWaterStage } from "@/components/home/HomeWaterStage"'), "assessment shell should reuse the shared home water stage")
  assert.ok(components.includes('background?: "default" | "home-water"'), "assessment shell should expose an explicit shared-water background mode")
  assert.ok(components.includes("<HomeWaterStage />"), "home-water mode should mount the shared water stage")
  assert.ok(components.includes('data-background={background}'), "assessment shell should expose the selected background for QA")
  assert.ok(components.includes('usesHomeWater ? "bg-[#050807]" : "bg-[#050504]"'), "shared-water shell should not expose the global warm body background while the water mounts")
  assert.equal(globals.includes("radial-gradient(circle at 16% 16%, rgba(216, 183, 111, 0.2)"), false, "global body should not leak a warm light source behind the entry transition")

  assert.ok(page.includes("consumeSkipEntryOpeningRitualOnce"), "entry should skip the opening seal once after phone archive")
  assert.ok(page.includes("useState(() => !consumeSkipEntryOpeningRitualOnce())"), "entry should decide opening state before rendering")
  assert.ok(page.includes("}, 5400)"), "opening seal copy should linger long enough to rise from still water")
  assert.ok(page.includes("ritual-opening-fade-out 900ms ease 4600ms forwards"), "opening seal should hold before fading into the question page")
  assert.ok(page.includes("ritual-opening-thoughts"), "opening seal should include a faint floating-thought field")
  assert.ok(page.includes("ritual-floating-mote"), "opening ritual should include reference-like small thought motes")
  assert.ok(page.includes("--mote-r: 0.6"), "opening motes should use the reference small-radius range")
  assert.ok(page.includes("--mote-life: 6900ms"), "opening motes should use the reference slow 4-7s life range")
  assert.ok(page.includes("ritual-floating-thought"), "opening ritual should style faint drifting thought text")
  assert.ok(page.includes("先看清这一念。"), "opening floating thoughts should frame the seal as seeing one thought")
  assert.ok(page.includes("会回来的。"), "opening should include varied faint thought copy sizes")
  assert.ok(page.includes("ritual-seal-appear 1800ms"), "opening seal should rise slowly instead of popping in")
  assert.ok(page.includes("ritual-opening-copy-in 1280ms"), "opening copy should fade in after the seal settles instead of appearing abruptly")
  assert.ok(page.includes("color: rgba(238, 243, 238, 0.78)"), "opening copy should be brighter while keeping a restrained ritual tone")
  assert.ok(page.includes("@keyframes ritual-floating-thought-rise"), "opening thoughts should rise and dissolve without becoming a page section")
  assert.ok(page.includes("animation-delay: 1700ms"), "pause instruction should wait after the main prompt")
  assert.ok(page.includes("animation-delay: 3500ms"), "ready button should appear after the forced pause")
  assert.ok(page.includes("color: #eef3ee"), "main ritual prompt should use the clean bright reference proof color")
  assert.ok(page.includes("text-shadow: 0 0 56px rgba(0, 0, 0, 0.58)"), "main ritual prompt should use a clean black support shadow")
  assert.ok(page.includes("ritual-still-seal"), "opening brand mark should stay visible on the first ritual screen")
  assert.ok(page.includes('<YangmingA1Mark className="ritual-seal-mark" width={112} height={104} />'), "opening brand mark should have intrinsic SVG size fallback")
  assert.ok(page.includes('<YangmingA1Mark className="ritual-seal-mark" width={66} height={61} />'), "question brand mark should have intrinsic SVG size fallback")
  assert.ok(page.includes("overflow: hidden;"), "seal containers should clip any abnormal SVG overflow")
  assert.ok(page.includes("max-width: 54%;"), "opening seal glyph should stay visually subordinate to the water doorway")
  assert.ok(page.includes("max-width: 48%;"), "question seal glyph should stay subtle after the opening")
  assert.ok(!page.includes("ritual-opening-water-still"), "opening should not add a second local water surface over the shared water")
  assert.ok(page.includes("ritual-late-seal"), "question screen should reveal a subtle foreground brand mark after the ready button")
  assert.ok(page.includes("YangmingA1Mark"), "entry ritual seals should use the vector A1 mark")
  assert.equal(page.includes("YangmingCharacterMark"), false, "entry should not inject brand character-system labels into the locked prompt")
  assert.equal(page.includes("心字，测评入口，观心"), false, "entry should not show auxiliary character-system state copy")
  assert.equal(page.includes("测评入口 / 观心"), false, "entry should keep the prompt free of product-state labels")
  assert.equal(page.includes("<span>照</span>"), false, "entry ritual seals must not render font-based zhao glyphs")
  assert.ok(page.includes("4300ms forwards"), "question screen seal should appear after the ready button begins showing")
  assert.ok(page.includes("router.push(target)"), "ready button should route directly into the full-screen water gateway")
  assert.ok(page.includes('const target = savedPhone ? "/assessment" : "/assessment-login"'), "ready button should keep the water gateway route after login")
  assert.ok(page.includes("markAssessmentGatewayOnce"), "ready button should explicitly authorize one water gateway entry")
  assert.ok(page.includes("isRoutingRef"), "ready button should guard double taps without changing the visible page")
  assert.ok(!page.includes("@keyframes ritual-still-water-in"), "entry page should leave water rendering to the shared HomeWaterStage")
  assert.ok(!page.includes("ritual-entry-breath"), "question screen should not add a local breathing halo over the shared water")
  assert.ok(page.includes("ritual-still-seal-breathe 5.6s"), "opening mark should keep the original seal-only breathing")
  assert.ok(page.includes("ritual-late-seal-breathe 6.4s"), "question mark should keep the original seal-only breathing")
  assert.ok(page.includes("@keyframes ritual-still-seal-breathe"), "opening seal breathing should be scoped to the mark container")
  assert.ok(page.includes("@keyframes ritual-late-seal-breathe"), "question seal breathing should be scoped to the mark container")
  assert.ok(!page.includes("水面入静"), "entry page should not pull water-gateway copy before the ready button")
  assert.ok(!page.includes("setIsEntering"), "ready button should not trigger an intermediate re-render state")
  assert.ok(!page.includes("照心将启"), "ready button should not render an intermediate entering state")
  assert.ok(!page.includes("先不判断行情。"), "entry page should leave the water-gateway copy to /assessment")
  assert.ok(!page.includes("showExitRitual"), "entry page should not render its own exit transition")
  assert.ok(!page.includes("ritual-exit-copy"), "entry page should not show the no-judgement line as a transition")
  assert.ok(!page.includes("ritual-exit-ripple"), "entry page should not render a separate water-ripple transition")
  assert.ok(!page.includes("ritual-rising-seal"), "exit transition should not show a seal glyph after the ready button")
  assert.ok(!page.includes("@keyframes ritual-seal-float"), "exit transition should not float a seal glyph")
  assert.ok(!page.includes("ritual-heart-lamp"), "question screen should not render a second seal before the button")
})
