import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

const homeShellUrl = new URL("./cinematic-home.tsx", import.meta.url)
const heroUrl = new URL("./hero-section.tsx", import.meta.url)
const storySectionsUrl = new URL("./story-sections.tsx", import.meta.url)
const stillHeroUrl = new URL("./HomeStillWaterHero.tsx", import.meta.url)
const stillHeroCssUrl = new URL("./HomeStillWaterHero.module.css", import.meta.url)
const heroRightWaitingMirrorUrl = new URL("./HeroRightWaitingMirror.tsx", import.meta.url)
const waterStageUrl = new URL("./HomeWaterStage.tsx", import.meta.url)
const waterStageCssUrl = new URL("./HomeWaterStage.module.css", import.meta.url)
const mindLakeBackdropUrl = new URL("./HomeMindLakeBackdrop.tsx", import.meta.url)
const mindLakeBackdropCssUrl = new URL("./HomeMindLakeBackdrop.module.css", import.meta.url)
const topNavUrl = new URL("./top-nav.tsx", import.meta.url)
const appBottomNavUrl = new URL("../app-bottom-nav.tsx", import.meta.url)
const layoutUrl = new URL("../../app/layout.tsx", import.meta.url)
const globalsCssUrl = new URL("../../app/globals.css", import.meta.url)
const reflectAliasUrl = new URL("../../app/reflect/page.tsx", import.meta.url)
const reviewAliasUrl = new URL("../../app/review/page.tsx", import.meta.url)
const tradeReviewAliasUrl = new URL("../../app/trade-review/page.tsx", import.meta.url)
const archiveAliasUrl = new URL("../../app/archive/page.tsx", import.meta.url)
const lakeAliasUrl = new URL("../../app/lake/page.tsx", import.meta.url)
const scrollAliasUrl = new URL("../../app/scroll/page.tsx", import.meta.url)
const meAliasUrl = new URL("../../app/me/page.tsx", import.meta.url)
const meArchiveAliasUrl = new URL("../../app/me/archive/page.tsx", import.meta.url)

test("home first viewport is a still-water seeing entrance", async () => {
  const homeShell = await readFile(homeShellUrl, "utf8")
  const hero = await readFile(heroUrl, "utf8")
  const storySections = await readFile(storySectionsUrl, "utf8")
  const stillHero = await readFile(stillHeroUrl, "utf8")
  const stillHeroCss = await readFile(stillHeroCssUrl, "utf8")
  const heroRightWaitingMirror = await readFile(heroRightWaitingMirrorUrl, "utf8")
  const waterStage = await readFile(waterStageUrl, "utf8")
  const waterStageCss = await readFile(waterStageCssUrl, "utf8")
  const mindLakeBackdrop = await readFile(mindLakeBackdropUrl, "utf8")
  const mindLakeBackdropCss = await readFile(mindLakeBackdropCssUrl, "utf8")
  const topNav = await readFile(topNavUrl, "utf8")
  const appBottomNav = await readFile(appBottomNavUrl, "utf8")
  const layout = await readFile(layoutUrl, "utf8")
  const globalsCss = await readFile(globalsCssUrl, "utf8")
  const reflectAlias = await readFile(reflectAliasUrl, "utf8")
  const reviewAlias = await readFile(reviewAliasUrl, "utf8")
  const tradeReviewAlias = await readFile(tradeReviewAliasUrl, "utf8")
  const archiveAlias = await readFile(archiveAliasUrl, "utf8")
  const lakeAlias = await readFile(lakeAliasUrl, "utf8")
  const scrollAlias = await readFile(scrollAliasUrl, "utf8")
  const meAlias = await readFile(meAliasUrl, "utf8")
  const meArchiveAlias = await readFile(meArchiveAliasUrl, "utf8")

  ;[
    "HomeWaterStage",
    "HeroSection",
    "StorySections",
  ].forEach((componentName) => {
    assert.ok(homeShell.includes(componentName), `missing home section: ${componentName}`)
  })
  ;[
    "MindJourneySection",
    "AiFocusSection",
    "PersonalityEntrySection",
  ].forEach((oldSectionName) => {
    assert.equal(homeShell.includes(oldSectionName), false, `${oldSectionName} should not bring back a second background seam`)
  })

  assert.ok(hero.includes("HomeStillWaterHero"), "HeroSection should delegate the first viewport to the still-water hero")
  assert.equal(hero.includes("InsightCard"), false, "first viewport must not restore the right-side function card")
  assert.ok(homeShell.includes("<HomeWaterStage />"), "home should mount one shared fixed water layer")
  assert.equal(homeShell.includes("home-breath"), false, "shared fixed water must not sit inside a filtered breathing container")
  assert.equal(homeShell.includes("InkMountainBackground"), false, "home should not restore the old per-page ink background")
  assert.equal(homeShell.includes("HomePerspectiveField"), false, "home should not add a second fixed atmosphere layer over the shared water")
  assert.equal(homeShell.includes("WaterRippleField"), false, "old global hero ripple layer should not compete with the canvas water")
  assert.ok(homeShell.includes("<HeroSection />"), "home should render the still-water first screen")
  assert.ok(homeShell.includes("<StorySections />"), "home should render the second and third breaths after the first screen")
  assert.equal(homeShell.includes("HomeGatesSection"), false, "home should not render the five-gate directory as the second screen")
  assert.equal(homeShell.includes("顺这片水，往下走"), false, "home should stay a single world-view entrance, not a directory scroll")
  assert.equal(homeShell.includes("PersonalityGrid"), false, "home should not turn the second breath into a product grid")
  assert.ok(homeShell.includes("本系统仅用于交易认知、行为训练与风险教育；"), "home should keep the compliance copy")
  assert.ok(homeShell.includes("不荐股、不喊单、不承诺收益。"), "home should keep the compliance copy")
  assert.ok(homeShell.includes("sticky bottom-[max(.75rem,env(safe-area-inset-bottom))]"), "home compliance should sit at the screen bottom safe area")
  assert.ok(homeShell.includes("text-[rgba(220,212,195,.32)]"), "home compliance should be visually quiet")
  assert.ok(homeShell.includes("pointer-events-none"), "home compliance should not block the final one-thought entrance")
  assert.ok(homeShell.includes("mt-24"), "home compliance should keep distance from the main third-breath story")

  assert.ok(waterStage.includes("canvasRef"), "shared water stage should own the only page-level canvas")
  assert.ok(waterStage.includes("ripplesRef"), "shared water stage should manage ripples")
  assert.ok(waterStage.includes("nextAuto"), "shared water stage should create restrained automatic ripples")
  assert.ok(waterStage.includes("createAutoRipple"), "shared water stage should create occasional water-breathing ripples")
  assert.ok(waterStage.includes("5200 + Math.random() * 4200"), "first automatic ripple should arrive after a quiet pause")
  assert.ok(waterStage.includes("6200 + Math.random() * 5200"), "automatic ripples should be visible without becoming busy")
  assert.ok(waterStage.includes("lightTint"), "shared water should adapt tint by time of day")
  assert.ok(waterStage.includes('color: "200,224,224"'), "shared water daytime tint should use the reference still-water tint")
  assert.ok(waterStage.includes("150,178,184"), "shared canvas glow should use the reference still-water light")
  assert.ok(waterStage.includes("drawGlow"), "shared water should keep canvas breathing glows")
  assert.equal(waterStage.includes("drawStillWaterGlints"), false, "shared water should not keep the old extra glint layer")
  assert.equal(waterStage.includes("motesRef"), false, "shared water should not keep the old floating mote layer")
  assert.equal(waterStage.includes("drawMote"), false, "shared water should not render old breathing motes")
  assert.ok(waterStage.includes("context.arc(ripple.x, ripple.y, ringRadius"), "ripples should return to calm circular rings")
  assert.equal(waterStage.includes("styles.layerHeartLake"), false, "shared water should not keep the old CSS heart-lake breathing layer")
  assert.equal(waterStage.includes("styles.layerSubtleGlow"), false, "shared water should not keep the old subtle glow layer")
  assert.equal(waterStage.includes("styles.layerMirrorAura"), false, "shared water should not keep the old mirror aura ring")
  assert.equal(waterStage.includes("styles.layerFloatingThoughts"), false, "shared water should not keep the old floating thought layer")
  assert.equal(waterStage.includes("styles.floatingThought"), false, "shared water should not render separate thought motes")
  assert.ok(waterStage.includes("0.25 + Math.random() * 0.5"), "automatic ripples should use the reference still-water field")
  assert.equal(waterStage.includes("drawRippleSegmentedRing"), false, "ripples should not be segmented around title text")
  assert.equal(waterStage.includes("bendRipplePoint"), false, "ripples should not deform around the title")
  assert.equal(waterStage.includes("getTitleObstruction"), false, "shared water should not need title-obstruction geometry")
  assert.ok(waterStage.includes("home-water-ripple"), "sections should be able to ask the one shared water to ripple")
  assert.ok(waterStage.includes("home-water-dive"), "home dive transition should deepen the one shared water")
  assert.equal(waterStage.includes("home-water-ripple-impact"), false, "shared circular ripples should not push title interactions")
  assert.equal(waterStage.includes("getTitleRecoil"), false, "shared water should not recoil away from the title")
  assert.equal(stillHero.includes("canvasRef"), false, "hero should not create a second water canvas")
  assert.ok(stillHero.includes("home-water-ripple"), "hero should trigger the shared water on entry")
  assert.ok(stillHero.includes("home-water-dive"), "hero should drive the shared water during the dive")
  assert.ok(stillHero.includes("HOME_DIVE_DURATION_MS = 2400"), "main one-thought entrance should leave enough time for a visible water descent")
  assert.ok(stillHero.includes("HOME_ROUTE_DELAY_MS = 2200"), "main one-thought entrance should delay routing until the descent has read visually")
  assert.ok(storySections.includes("enterReflectThroughWater"), "final one-thought entrance should use the same water route transition")
  assert.ok(storySections.includes("home-water-dive"), "final one-thought entrance should deepen the shared water before routing")
  assert.ok(storySections.includes('REFLECT_ENTRY_HREF = "/assessment-entry"'), "final one-thought entrance should enter through the assessment-entry seal")
  assert.ok(storySections.includes('document.documentElement.setAttribute("data-home-route-transition", "active")'), "final one-thought entrance should mark the shared route transition")
  assert.ok(storySections.includes('document.documentElement.setAttribute("data-home-story-scrollbar", "quiet")'), "home story should quiet the native page scrollbar only while mounted")
  assert.ok(storySections.includes('document.documentElement.removeAttribute("data-home-story-scrollbar")'), "home story should restore the page scrollbar when unmounted")
  assert.ok(storySections.includes("HOME_ROUTE_DELAY_MS = 2200"), "final one-thought entrance should wait for the water descent")
  assert.ok(storySections.includes("relative z-20 min-h-[230svh]"), "three-breath story should sit above the compliance footer while pinned")
  assert.ok(storySections.includes('data-third-phase="closure"'), "third breath should keep the final doorway in its own closing phase")
  assert.ok(storySections.includes("pt-[12svh]"), "third breath final doorway should sit slightly below center with cleaner upper space")
  assert.equal(stillHero.includes("home-water-ripple-impact"), false, "hero text should stay still while water reacts around it")
  assert.ok(stillHero.includes('className={styles.zhaoMark}'), "hero should use a dedicated artistic 照 seal")
  assert.ok(stillHero.includes("YangmingA1Mark"), "hero seal should use the project brand art glyph")
  assert.equal(stillHero.includes(">照</span>"), false, "hero seal should not fall back to a font-based 照")
  assert.equal(stillHero.includes("feTurbulence"), false, "hero title should not use a water-ink filter that dulls the glyphs")
  assert.equal(stillHero.includes("feDisplacementMap"), false, "hero title should stay clean instead of displaced")
  assert.equal(stillHeroCss.includes('filter: url("#home-still-water-ink")'), false, "hero title should not carry the old SVG ink filter")
  assert.ok(stillHero.includes("data-hero-title"), "hero title should expose a target for water-title interaction")
  assert.ok(stillHero.includes("HeroRightWaitingMirror"), "hero should place the waiting mirror into the empty right-side visual field")
  assert.equal(stillHero.includes("HeroRightZhaoSeal"), false, "home hero should not use the completed-state zhao seal")
  assert.ok(stillHero.includes("className={styles.rightSealStage}"), "right-side mirror should live in the existing dedicated visual area")
  assert.ok(heroRightWaitingMirror.includes("function HeroRightWaitingMirror"), "right-side waiting mirror should be its own home component")
  assert.ok(heroRightWaitingMirror.includes("<figure"), "right-side waiting mirror should be semantic display, not a control")
  assert.ok(heroRightWaitingMirror.includes("待照心镜，观心系统待照一念"), "right-side waiting mirror should expose a quiet descriptive label")
  assert.ok(heroRightWaitingMirror.includes("待 照"), "right-side waiting mirror should show the faint waiting text")
  assert.ok(heroRightWaitingMirror.includes("观心系统 · 待照一念"), "right-side waiting mirror should settle as 待照一念, not a loading state")
  assert.equal(heroRightWaitingMirror.includes("心 镜 · 照 印"), false, "home waiting mirror should not look like the completed zhao seal")
  assert.equal(heroRightWaitingMirror.includes("照　见"), false, "home waiting mirror should not reuse the completed seal wordmark")
  assert.equal(heroRightWaitingMirror.includes(">照</text>"), false, "home waiting mirror should not show a giant completed-state 照 glyph")
  assert.equal(heroRightWaitingMirror.includes("正在显影"), false, "right-side waiting mirror status should not look like a permanent loading state")
  assert.equal(heroRightWaitingMirror.includes("<button"), false, "right-side waiting mirror must not be a button")
  assert.equal(heroRightWaitingMirror.includes("cursor: pointer"), false, "right-side waiting mirror must not imply it is clickable")
  assert.equal(heroRightWaitingMirror.includes("点一下，重新显影"), false, "right-side waiting mirror must not expose replay affordance")
  assert.equal(heroRightWaitingMirror.includes("href="), false, "right-side waiting mirror must not navigate")
  assert.equal(heroRightWaitingMirror.includes("onClick"), false, "right-side waiting mirror must not trigger the ritual")
  assert.equal(heroRightWaitingMirror.includes("router.push"), false, "right-side waiting mirror must not route anywhere")
  assert.equal(heroRightWaitingMirror.includes("OneThoughtRitual"), false, "right-side waiting mirror must not touch the ritual")
  assert.equal(heroRightWaitingMirror.includes('id="zy-pool"'), false, "waiting mirror should avoid fixed SVG ids")
  assert.equal(heroRightWaitingMirror.includes('id="zy-h"'), false, "waiting mirror should avoid fixed SVG ids")
  assert.equal(heroRightWaitingMirror.includes('id="zy-c"'), false, "waiting mirror should avoid fixed SVG ids")
  assert.ok(heroRightWaitingMirror.includes("useId().replace"), "waiting mirror should namespace SVG ids")
  assert.ok(heroRightWaitingMirror.includes("@media (prefers-reduced-motion: reduce)"), "waiting mirror should respect reduced motion")
  assert.ok(heroRightWaitingMirror.includes("pointer-events: none"), "right-side waiting mirror should not intercept the main CTA")
  assert.ok(stillHeroCss.includes(".rightSealStage"), "hero CSS should position the right-side mirror stage")
  assert.ok(stillHeroCss.includes(".rightSealWatermark"), "mobile hero should reduce the right-side mirror into a watermark")
  assert.ok(stillHeroCss.includes("width: clamp(96px, 28vw, 140px) !important"), "mobile waiting mirror should shrink into a small watermark")
  assert.ok(stillHero.includes("心不静，"), "hero should keep the brand title")
  assert.ok(stillHero.includes("交易必乱。"), "hero should keep the brand title")
  assert.ok(stillHero.includes("市场照见价格 · 心镜照见自己"), "hero should keep the soul line")
  assert.ok(stillHero.includes("今天，你起了哪一念？"), "hero should ask today's one-thought question")
  assert.ok(stillHero.includes("styles.entryGroup"), "one-thought question and doorway should stay bound as one visual group")
  assert.ok(stillHero.includes('REFLECT_ENTRY_HREF = "/assessment-entry"'), "main threshold should enter the assessment-entry seal")
  assert.equal(stillHero.includes('href="/review"'), false, "first viewport should not include a secondary review entrance")
  assert.ok(stillHero.includes("照见一念"), "main threshold should say 照见一念")
  assert.equal(stillHero.includes("今日入卷"), false, "main threshold should not keep an extra caption")
  assert.equal(stillHero.includes("照见实盘"), false, "first viewport should keep one doorway and no secondary review copy")
  assert.equal(stillHero.includes("今日照见台"), false, "right-side seeing platform must stay out of the first viewport")
  assert.equal(stillHero.includes("不急翻回"), false, "right-side card copy must stay out of the first viewport")
  assert.equal(stillHero.includes("写下此刻心里那句话"), false, "home threshold should not contain the one-thought-lake writing ritual")
  assert.equal(stillHero.includes("市场未动，心已先动"), false, "home threshold should not pause on the lake writing prompt")
  assert.equal(stillHero.includes("落入水中"), false, "home threshold should route through water instead of opening a second input step")
  assert.equal(stillHero.includes("typedThought"), false, "home threshold should not own one-thought input state")

  ;[
    "你以为你输给了行情。",
    "其实很多时候，",
    "是下单前那一念，",
    "先替你做了主。",
    "照见不是预测。",
    "下单前那一念",
    "照出来。",
    "比如：",
    "「再等等。」",
    "你等的不是机会。",
    "你等的是，",
    "一个不用认错的台阶。",
    "照见一念",
    "照回",
    "今天，",
    "你起了哪一念？",
  ].forEach((copy) => {
    assert.ok(storySections.includes(copy), `three-breath story missing copy: ${copy}`)
  })
  assert.ok(storySections.includes('href={REFLECT_ENTRY_HREF}'), "third breath should return naturally to the assessment-entry seal")
  assert.ok(storySections.includes("onMouseEnter={previewReflectRipple}"), "third-breath entrance should create a light water ripple on hover")
  assert.ok(storySections.includes("strength: 0.12"), "third-breath hover ripple should stay restrained")
  assert.ok(storySections.includes("data-breath-line"), "second breath should reveal lines one at a time")
  assert.equal(storySections.includes("data-breath-small"), false, "second breath should end as four lines before the third breath begins")
  assert.equal(storySections.includes("追高、扛单、补仓、翻本、怕卖飞……"), false, "second breath should not keep the old supporting copy in this tighter sequence")
  assert.equal(storySections.includes("每一次失控，"), false, "second breath should not overlap with third-breath sample setup")
  assert.ok(storySections.includes('data-third-phase="law"'), "third breath should split the method statement into its own phase")
  assert.ok(storySections.includes('data-third-phase="thought"'), "third breath should split the sample thought into its own phase")
  assert.ok(storySections.includes('data-third-phase="reflection"'), "third breath should split the reflection strike into its own phase")
  assert.ok(storySections.includes('data-third-phase="closure"'), "third breath should split the closing practice and entrance into its own phase")
  assert.ok(storySections.includes("data-third-opening"), "third breath should introduce seeing as non-prediction")
  assert.ok(storySections.includes("data-sample-thought"), "third breath should show one concrete thought sample")
  assert.ok(storySections.includes("data-sample-reflection=\"pain\""), "third breath should make the reflection pain point explicit")
  assert.equal(storySections.includes("data-sample-close"), false, "final third-breath screen should not keep the thief/practice aftertone")
  assert.equal(storySections.includes("data-method-chain"), false, "final third-breath screen should not keep the method-chain ghost")
  assert.ok(storySections.includes("const activePhase"), "third breath should use one clear active phase instead of a static poster")
  assert.ok(storySections.includes("const previousPhase"), "third breath should push the previous phase back into mist")
  assert.ok(storySections.includes("const quietPhase"), "third breath should keep next phases hidden")
  assert.ok(storySections.includes('pointerEvents: "none"'), "hidden third-breath phases should not block the final entrance")
  assert.ok(storySections.includes('pointerEvents: "auto"'), "the closing phase should restore click access to the final entrance")
  assert.ok(storySections.includes("perspective: 1100"), "three-breath story should use restrained text depth")
  assert.ok(storySections.includes("const firstSecondLine"), "second breath should begin before the first-to-second transition becomes empty")
  assert.ok(storySections.includes("opacity: 0.98"), "first second-breath line should be immediately clear")
  assert.ok(storySections.includes("const secondDepthLines"), "second-breath supporting lines should be staged instead of appearing all at once")
  assert.ok(storySections.includes("const secondLineRevealPlan"), "second-breath four-line照回 should reveal one beat at a time")
  assert.ok(storySections.includes("{ index: 3, at: 4.1"), "the final second-breath line should arrive as the last beat")
  assert.ok(storySections.includes("-top-[12svh]"), "second breath should sit high enough to reduce the gap without clipping the four-line照回")
  assert.ok(storySections.includes("items-start justify-center pt-[14svh]"), "three-breath stage should start higher to reduce the gap after the first viewport")
  assert.ok(storySections.includes('filter: "blur(0px)"'), "second-breath key copy should stay sharp instead of being hidden in water mist")
  assert.ok(storySections.includes("scale: 0.98"), "distant words should begin slightly smaller without feeling unreachable")
  assert.ok(storySections.includes("scale: 1.018"), "the final second-breath beat should approach slightly without becoming flashy")
  assert.ok(storySections.includes("data-sample-reflection-label"), "third-breath reflection label should stay lighter than the reflection copy")
  assert.ok(storySections.includes("sampleReflectionPain"), "third-breath reflection should have a distinct second beat")
  assert.ok(storySections.includes("rgba(216,183,111,.035)"), "sample thought water mark should stay below card-like visibility")
  assert.ok(storySections.includes("text-[rgba(216,183,111,.42)]"), "sample marker should stay light")
  assert.ok(storySections.includes("opacity: 0.18"), "previous phases should stay faint when receding")
  assert.ok(storySections.includes(".to(reflectionPhase, quietPhase, 15.05)"), "the reflection strike should fully dissolve before the final doorway")
  assert.ok(storySections.includes('filter: "blur(10px)"'), "leaving panels should soften into mist without making the story unreadable")
  assert.ok(storySections.includes("text-[rgba(238,243,238,.94)]"), "second-breath main copy should be bright enough to read at a glance")
  assert.ok(storySections.includes("relative flex min-h-[24rem]"), "second-breath key copy should be a readable four-line block, not overlapping hidden text")
  assert.ok(storySections.includes("text-[rgba(238,243,238,.96)]"), "third-breath method words should read clearly when current")
  assert.ok(storySections.includes("下单前那一念"), "the key second-breath phrase should be available for brighter styling")
  assert.ok(storySections.includes("7.25"), "second breath should hold its final line before fading out")
  assert.ok(storySections.includes("8.45"), "third breath should begin only after the second breath has completed")
  assert.ok(storySections.includes("finalCall"), "third-breath final entrance should be revealed as the last phase")
  assert.equal(storySections.includes("mt-12"), false, "third-breath final doorway should not have a lower aftertone block")
  assert.ok(storySections.includes('data-story-door="third"'), "third-breath final entrance should use a larger story-only doorway")
  assert.ok(stillHeroCss.includes('.door[data-story-door="third"] .doorMain'), "third-breath doorway sizing should not change the first-screen doorway")
  assert.ok(stillHeroCss.includes("font-size: clamp(34px, 3.6vw, 52px)"), "third-breath doorway should be large enough to read as an entrance")
  assert.ok(stillHeroCss.includes("width: clamp(180px, 19vw, 260px)"), "third-breath doorway line should stay within the requested range")
  assert.equal(storySections.includes("看见谁在下单。"), false, "third breath should not keep the old abstract method line as the main story")
  assert.equal(storySections.includes("把它落成今日修行。"), false, "third breath should not keep the old abstract method line as the main story")
  assert.equal(storySections.includes("不是压住情绪。"), false, "third breath should use the concrete sample instead of the old explanatory copy")
  assert.equal(storySections.includes("恐惧"), false, "story should not render the old emotion orbit")
  assert.equal(storySections.includes("贪婪"), false, "story should not render the old emotion orbit")
  assert.equal(storySections.includes("急躁"), false, "story should not render the old emotion orbit")
  assert.equal(storySections.includes("幻想"), false, "story should not render the old emotion orbit")
  assert.equal(storySections.includes("九型交易人格"), false, "home story should not become a personality feature intro")
  assert.equal(storySections.includes("五层训练系统"), false, "home story should not become a training feature intro")
  assert.equal(storySections.includes("Dashboard"), false, "home story should not read like a SaaS dashboard")
  assert.equal(storySections.includes("rounded-"), false, "three-breath story should avoid card-like rounded surfaces")

  assert.ok(waterStageCss.includes("position: fixed"), "shared water should be fixed to the viewport")
  assert.ok(waterStageCss.includes("radial-gradient(120% 100% at 42% 52%"), "shared water should use the clean reference still-water base")
  assert.ok(waterStageCss.includes("#0e1819"), "shared water base should keep the reference ink-green depth")
  assert.ok(waterStageCss.includes("height: 100svh"), "shared water should stay viewport-sized instead of growing to the whole page")
  assert.ok(waterStageCss.includes("contain: strict"), "shared water should isolate its canvas work from page layout")
  assert.ok(waterStageCss.includes(".canvas"), "shared water canvas should be styled in the water stage")
  assert.ok(waterStageCss.includes(".tintLayer"), "shared water should keep time-of-day tint")
  assert.equal(waterStageCss.includes(".surfaceLayer"), false, "shared water should not keep the old extra surface light layer")
  assert.equal(waterStageCss.includes(".layerHeartLake"), false, "shared water should not style the old heart-lake base layer")
  assert.equal(waterStageCss.includes("animation: heartLakeBreath"), false, "shared water should remove the old CSS brightness breathing")
  assert.equal(waterStageCss.includes(".layerSubtleGlow"), false, "shared water should not style the old subtle underwater glow")
  assert.equal(waterStageCss.includes("animation: subtleGlowDrift"), false, "shared water should not keep the old drifting glow")
  assert.equal(waterStageCss.includes(".stillWaterPlane"), false, "shared water should not keep the old still-water plane")
  assert.equal(waterStageCss.includes("animation: stillWaterBreath"), false, "shared water should remove the visible CSS water-plane breathing")
  assert.equal(waterStageCss.includes(".layerMirrorAura"), false, "shared water should not style the old mirror aura layer")
  assert.equal(waterStageCss.includes(".mirrorAura"), false, "shared water should not keep the old visible mirror aura ring")
  assert.equal(waterStageCss.includes(".layerFloatingThoughts"), false, "shared water should not style separate floating thought lights")
  assert.equal(waterStageCss.includes("animation: thoughtDrift"), false, "shared water should not keep the old CSS thought drift layer")
  assert.ok(waterStageCss.includes(".deepLayer"), "shared water should deepen during the dive transition")
  assert.ok(waterStageCss.includes(".vignetteLayer"), "shared water should keep the page-level vignette")
  assert.ok(waterStageCss.includes("rgba(0, 0, 0, 0.55)"), "shared water should carry the reference edge vignette")
  assert.ok(waterStageCss.includes("@media (prefers-reduced-motion: reduce)"), "shared water should respect reduced motion")
  assert.ok(waterStageCss.includes(".canvas,\n  .tintLayer,\n  .deepLayer"), "shared water should reduce transition motion for the remaining pure background layers")
  assert.ok(globalsCss.includes('html[data-home-story-scrollbar="quiet"]'), "home story scrollbar styling should be scoped to the home story marker")
  assert.ok(globalsCss.includes("width: 4px"), "desktop home story scrollbar should be very thin")
  assert.ok(globalsCss.includes("rgba(184, 154, 88, 0.18)"), "desktop home story scrollbar thumb should stay low-contrast gold")
  assert.ok(globalsCss.includes("scrollbar-width: thin"), "Firefox desktop home story scrollbar should be thin")
  assert.ok(globalsCss.includes("scrollbar-width: none"), "mobile home story scrollbar should be hidden")
  assert.ok(globalsCss.includes("display: none"), "mobile WebKit home story scrollbar should be hidden")
  assert.ok(mindLakeBackdrop.includes("styles.layerSubtleGlow"), "legacy mind-lake backdrop should include the subtle underwater glow")
  assert.ok(mindLakeBackdropCss.includes("animation: heartLakeBreath 22s"), "legacy heart lake should use the slower breathing cadence")
  assert.ok(mindLakeBackdropCss.includes("animation: stillWaterBreath 18s"), "legacy still water should use the slower breathing cadence")
  assert.ok(mindLakeBackdropCss.includes("animation: mirrorAuraBreath 24s"), "legacy mirror aura should use the slower breathing cadence")
  assert.ok(mindLakeBackdropCss.includes("animation: subtleGlowDrift 28s"), "legacy mind-lake glow should drift very slowly")
  assert.ok(mindLakeBackdropCss.includes(".floatingThought"), "legacy mind-lake floating thoughts should stay restrained")
  assert.ok(mindLakeBackdropCss.includes("@media (prefers-reduced-motion: reduce)"), "legacy mind-lake backdrop should respect reduced motion")
  assert.equal(stillHeroCss.includes(".waterCanvas"), false, "hero CSS should not keep its own water canvas")
  assert.ok(stillHeroCss.includes("white-space: nowrap"), "hero title lines should not split the maxim mid-phrase")
  assert.equal(stillHeroCss.includes("--ripple-push-x"), false, "hero title should not be pushed by ripples")
  assert.equal(stillHeroCss.includes("--ripple-title-blur"), false, "hero title should not blur when ripples pass")
  assert.ok(stillHeroCss.includes(".zhaoMark"), "hero should position the artistic 照 seal")
  assert.ok(stillHeroCss.includes("color: #eef3ee"), "hero title should use the clean bright reference proof color")
  assert.ok(stillHeroCss.includes("text-shadow: 0 0 60px rgba(0, 0, 0, 0.6)"), "hero title should use a clean black support shadow instead of warm glow")
  assert.ok(stillHeroCss.includes("color: rgba(255, 255, 255, 0.96)"), "market half of the soul line should stay bright while keeping its original white role")
  assert.ok(stillHeroCss.includes("color: rgba(242, 209, 132, 0.98)"), "mirror half of the soul line should keep its gold role while becoming brighter")
  assert.ok(stillHeroCss.includes("background: linear-gradient(90deg, rgba(242, 209, 132, 0.66)"), "main entrance line should keep the gold doorway language")
  assert.ok(topNav.includes("home-nav-zhao"), "top nav should use the same seal container language")
  assert.ok(topNav.includes("YangmingA1Mark"), "top nav seal should use the project brand art glyph")
  assert.ok(topNav.includes("getSavedPhoneTail"), "top nav should read the saved phone tail for the first-screen account chip")
  assert.ok(topNav.includes("getSavedNickname"), "top nav should read the saved nickname for the first-screen account chip")
  assert.ok(topNav.includes("home-account-chip"), "top nav should expose the quiet first-screen account chip")
  assert.ok(topNav.includes("home-account-panel"), "top nav should let the account chip open basic information")
  assert.ok(topNav.includes("setStorage(assessmentStorageKeys.userNickname"), "top nav account panel should let the user update a nickname")
  assert.ok(topNav.includes("退出照心账户"), "top nav account panel should let developers and users return to the new-user flow")
  assert.ok(topNav.includes("removeStorage(assessmentStorageKeys.userPhone)"), "signing out should clear the saved phone")
  assert.ok(topNav.includes("removeStorage(assessmentStorageKeys.phoneTail)"), "signing out should clear the phone tail shown in the nav")
  assert.ok(topNav.includes("window.localStorage.removeItem(STORAGE_KEYS.homeIntroSeen)"), "signing out should clear the home intro visitor flag")
  assert.ok(topNav.includes("window.localStorage.removeItem(STORAGE_KEYS.firstReflectEntered)"), "signing out should clear the reflect visitor flag")
  assert.equal(topNav.includes("clearVisitorStateForDevOnly"), false, "signing out should not wipe archived one-thought records")
  assert.equal(topNav.includes("STORAGE_KEYS.insightRecords"), false, "signing out should not delete sealed archive records")
  assert.ok(topNav.includes("window.scrollY"), "top nav should fade according to real page scroll")
  assert.ok(topNav.includes("viewportHeight * 0.5"), "top nav should fully hide after about half a viewport")
  assert.ok(topNav.includes("scrollFade > 0.08"), "top nav should disable pointer events once it has faded away")
  assert.ok(topNav.includes("enterRouteThroughWater"), "home nav links should enter routes through the water transition")
  assert.ok(topNav.includes("data-home-route-transition"), "home nav transition should mark the document during route entry")
  assert.ok(topNav.includes("home-water-ripple"), "home nav transition should reuse the shared water ripple")
  assert.ok(topNav.includes("home-water-dive"), "home nav transition should reuse the shared water dive")
  assert.ok(topNav.includes("HOME_DIVE_DURATION_MS = 2400"), "home nav transitions should share the slower dive cadence")
  assert.ok(topNav.includes("HOME_ROUTE_DELAY_MS = 2200"), "home nav routing should wait for the water transition")
  assert.ok(topNav.includes("router.push(href)"), "home nav transition should route after the water entry")
  assert.ok(stillHeroCss.includes(".door"), "main entrance should be styled as a threshold")
  assert.ok(stillHeroCss.includes(".doorLine"), "main entrance should use a breathing fine line")
  assert.ok(stillHeroCss.includes(".entryGroup"), "one-thought entrance should keep a shared alignment wrapper")
  assert.ok(stillHeroCss.includes("gap: clamp(0.5rem, 1vh, 0.75rem)"), "one-thought question and doorway should stay tightly grouped")
  assert.ok(stillHeroCss.includes(':global(html[data-home-route-transition="active"]) .content'), "home route transition should sink the first viewport content")
  assert.equal(stillHeroCss.includes("rounded-full border px-6"), false, "main entrance should not look like a pill CTA button")
  assert.ok(stillHeroCss.includes("@media (prefers-reduced-motion: reduce)"), "hero should respect reduced motion")

  ;["股票", "代码", "收益", "涨跌", "买入", "卖出", "BTC", "AAPL"].forEach((forbiddenMarketToken) => {
    assert.equal(stillHero.includes(forbiddenMarketToken), false, `hero should not include readable market info: ${forbiddenMarketToken}`)
  })

  ;["/today-sealed", "/review", "/mind-archive", "/lake"].forEach((href) => {
    assert.ok(topNav.includes(`href: "${href}"`), `home nav missing route: ${href}`)
  })
  assert.ok(topNav.includes("privateNavLinks"), "home top nav should keep private route group separate")
  assert.ok(topNav.includes("publicNavLinks"), "home top nav should keep public route group separate")
  assert.ok(topNav.includes("home-nav-divider"), "home top nav should visually separate public lake from private routes")
  assert.equal(topNav.includes("one-thought-bottom-nav"), false, "home top nav should not include the app bottom nav")
  assert.equal(topNav.includes("<FlowButton"), false, "home nav should not keep a duplicate top-right one-thought entrance")
  assert.equal(topNav.includes("照见一念"), false, "home nav should leave 照见一念 to the main hero doorway")
  assert.ok(topNav.includes("今日所照"), "home top nav should expose today's sealed-record status page")
  assert.ok(topNav.includes("真实复盘"), "home top nav should expose the one-thought trade review pillar")
  assert.ok(topNav.includes("档案馆"), "home top nav should expose the private archive museum")
  assert.ok(topNav.includes("众念心湖"), "home top nav should expose the public lake")
  assert.equal(topNav.includes('{ label: "一念档案"'), false, "home top nav should not duplicate the archive museum label")
  assert.equal(topNav.includes('{ label: "今日照见", href: "/reflect" }'), false, "home top nav should not duplicate the private start flow")
  assert.ok(layout.includes("<AppBottomNav />"), "app layout should mount bottom navigation outside the home-only top nav")
  ;["今日照见", "心镜长卷", "众念心湖", "我的", 'href: "/reflect"', 'href: "/scroll"', 'href: "/lake"', 'href: "/me"'].forEach((copy) => {
    assert.ok(appBottomNav.includes(copy), `app bottom nav missing: ${copy}`)
  })
  assert.ok(appBottomNav.includes("shouldShowBottomNav"), "bottom nav should be route-scoped instead of shown on the home page")
  assert.match(reflectAlias, /getTodayInsightRecord/)
  assert.match(reviewAlias, /ReviewPageContent/)
  assert.match(reviewAlias, /createTradeReview/)
  assert.match(tradeReviewAlias, /redirect\("\/review"\)/)
  assert.match(archiveAlias, /redirect\("\/mind-archive"\)/)
  assert.match(lakeAlias, /<OneThoughtLakePage \/>/)
  assert.match(scrollAlias, /redirect\("\/mirror-scroll"\)/)
  assert.match(meAlias, /redirect\("\/me\/archive"\)/)
  assert.match(meArchiveAlias, /redirect\("\/mind-archive"\)/)
})
