import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

const homeShellUrl = new URL("./cinematic-home.tsx", import.meta.url)
const heroUrl = new URL("./hero-section.tsx", import.meta.url)
const stillHeroUrl = new URL("./HomeStillWaterHero.tsx", import.meta.url)
const stillHeroCssUrl = new URL("./HomeStillWaterHero.module.css", import.meta.url)
const waterStageUrl = new URL("./HomeWaterStage.tsx", import.meta.url)
const waterStageCssUrl = new URL("./HomeWaterStage.module.css", import.meta.url)
const gatesUrl = new URL("./HomeGatesSection.tsx", import.meta.url)
const gatesCssUrl = new URL("./HomeGatesSection.module.css", import.meta.url)
const topNavUrl = new URL("./top-nav.tsx", import.meta.url)
const reflectAliasUrl = new URL("../../app/reflect/page.tsx", import.meta.url)
const reviewAliasUrl = new URL("../../app/review/page.tsx", import.meta.url)
const lakeAliasUrl = new URL("../../app/lake/page.tsx", import.meta.url)

test("home first viewport is a still-water seeing entrance", async () => {
  const homeShell = await readFile(homeShellUrl, "utf8")
  const hero = await readFile(heroUrl, "utf8")
  const stillHero = await readFile(stillHeroUrl, "utf8")
  const stillHeroCss = await readFile(stillHeroCssUrl, "utf8")
  const waterStage = await readFile(waterStageUrl, "utf8")
  const waterStageCss = await readFile(waterStageCssUrl, "utf8")
  const gates = await readFile(gatesUrl, "utf8")
  const gatesCss = await readFile(gatesCssUrl, "utf8")
  const topNav = await readFile(topNavUrl, "utf8")
  const reflectAlias = await readFile(reflectAliasUrl, "utf8")
  const reviewAlias = await readFile(reviewAliasUrl, "utf8")
  const lakeAlias = await readFile(lakeAliasUrl, "utf8")

  ;[
    "HomeWaterStage",
    "HeroSection",
    "HomeGatesSection",
  ].forEach((componentName) => {
    assert.ok(homeShell.includes(componentName), `missing home section: ${componentName}`)
  })
  ;[
    "MindJourneySection",
    "AiFocusSection",
    "PersonalityEntrySection",
  ].forEach((oldSectionName) => {
    assert.equal(homeShell.includes(oldSectionName), false, `${oldSectionName} should not bring back a second background seam`)
  })

  assert.ok(hero.includes("HomeStillWaterHero"), "HeroSection should delegate the first viewport to the still-water hero")
  assert.equal(hero.includes("InsightCard"), false, "first viewport must not restore the right-side function card")
  assert.ok(homeShell.includes("<HomeWaterStage />"), "home should mount one shared fixed water layer")
  assert.equal(homeShell.includes("home-breath"), false, "shared fixed water must not sit inside a filtered breathing container")
  assert.equal(homeShell.includes("InkMountainBackground"), false, "home should not restore the old per-page ink background")
  assert.equal(homeShell.includes("HomePerspectiveField"), false, "home should not add a second fixed atmosphere layer over the shared water")
  assert.equal(homeShell.includes("WaterRippleField"), false, "old global hero ripple layer should not compete with the canvas water")
  assert.ok(homeShell.includes("<HeroSection />"), "home should render the still-water first screen")
  assert.ok(homeShell.includes("<HomeGatesSection />"), "home should render gates as the second screen")
  assert.ok(homeShell.indexOf("<HeroSection />") < homeShell.indexOf("<HomeGatesSection />"), "gates should come after the still-water hero")
  assert.ok(homeShell.indexOf("<HeroSection />") < homeShell.indexOf("<HomeGatesSection />"), "the page should move from one breath into the five gates")

  assert.ok(waterStage.includes("canvasRef"), "shared water stage should own the only page-level canvas")
  assert.ok(waterStage.includes("ripplesRef"), "shared water stage should manage ripples")
  assert.ok(waterStage.includes("nextAuto"), "shared water stage should create restrained automatic ripples")
  assert.ok(waterStage.includes("createAutoRipple"), "shared water stage should create occasional water-breathing ripples")
  assert.ok(waterStage.includes("2100 + Math.random() * 3400"), "automatic ripples should have a visible but restrained life cadence")
  assert.ok(waterStage.includes("lightTint"), "shared water should adapt tint by time of day")
  assert.ok(waterStage.includes("drawGlow"), "shared water should keep canvas breathing glows")
  assert.ok(waterStage.includes("drawStillWaterGlints"), "shared water should keep subtle water glints")
  assert.ok(waterStage.includes("motesRef"), "shared water should keep faint floating motes and bubbles")
  assert.ok(waterStage.includes("drawMote"), "shared water should render breathing motes during ordinary water and dive states")
  assert.ok(waterStage.includes("context.arc(centerX, centerY, ringRadius"), "ripples should return to calm circular rings")
  assert.equal(waterStage.includes("drawRippleSegmentedRing"), false, "ripples should not be segmented around title text")
  assert.equal(waterStage.includes("bendRipplePoint"), false, "ripples should not deform around the title")
  assert.equal(waterStage.includes("getTitleObstruction"), false, "shared water should not need title-obstruction geometry")
  assert.ok(waterStage.includes("home-water-ripple"), "sections should be able to ask the one shared water to ripple")
  assert.ok(waterStage.includes("home-water-dive"), "home dive transition should deepen the one shared water")
  assert.equal(waterStage.includes("home-water-ripple-impact"), false, "shared circular ripples should not push title interactions")
  assert.equal(waterStage.includes("getTitleRecoil"), false, "shared water should not recoil away from the title")
  assert.equal(stillHero.includes("canvasRef"), false, "hero should not create a second water canvas")
  assert.ok(stillHero.includes("home-water-ripple"), "hero should trigger the shared water on entry")
  assert.ok(stillHero.includes("home-water-dive"), "hero should drive the shared water during the dive")
  assert.equal(stillHero.includes("home-water-ripple-impact"), false, "hero text should stay still while water reacts around it")
  assert.ok(stillHero.includes('className={styles.zhaoMark}'), "hero should use a dedicated artistic 照 seal")
  assert.ok(stillHero.includes("YangmingA1Mark"), "hero seal should use the project brand art glyph")
  assert.equal(stillHero.includes(">照</span>"), false, "hero seal should not fall back to a font-based 照")
  assert.ok(stillHero.includes("feTurbulence"), "title should have a restrained ink turbulence filter")
  assert.ok(stillHero.includes("feDisplacementMap"), "title should have a restrained ink displacement filter")
  assert.ok(stillHero.includes('scale="3.2"'), "ink displacement should not exceed the requested scale")
  assert.ok(stillHero.includes("data-hero-title"), "hero title should expose a target for water-title interaction")
  assert.ok(stillHero.includes("心不静，"), "hero should keep the brand title")
  assert.ok(stillHero.includes("交易必乱。"), "hero should keep the brand title")
  assert.ok(stillHero.includes("市场照见价格 · 心镜照见自己"), "hero should keep the soul line")
  assert.ok(stillHero.includes("这不是一个预测行情的网站，而是一套帮助交易者照见自己、重建纪律、训练执行的心学系统。"), "hero should keep the clear positioning line")
  assert.ok(stillHero.includes('href="/reflect"'), "main threshold should enter /reflect")
  assert.equal(stillHero.includes('href="/review"'), false, "first viewport should not include a secondary review entrance")
  assert.ok(stillHero.includes("照见一念"), "main threshold should say 照见一念")
  assert.ok(stillHero.includes("今日入卷"), "main threshold should keep the 今日入卷 caption")
  assert.equal(stillHero.includes("照见实盘"), false, "first viewport should keep one doorway and no secondary review copy")
  assert.equal(stillHero.includes("今日照见台"), false, "right-side seeing platform must stay out of the first viewport")
  assert.equal(stillHero.includes("不急翻回"), false, "right-side card copy must stay out of the first viewport")

  assert.ok(waterStageCss.includes("position: fixed"), "shared water should be fixed to the viewport")
  assert.ok(waterStageCss.includes("height: 100svh"), "shared water should stay viewport-sized instead of growing to the whole page")
  assert.ok(waterStageCss.includes("contain: strict"), "shared water should isolate its canvas work from page layout")
  assert.ok(waterStageCss.includes(".canvas"), "shared water canvas should be styled in the water stage")
  assert.ok(waterStageCss.includes(".surfaceLayer"), "shared water should keep the original surface light layer")
  assert.ok(waterStageCss.includes(".tintLayer"), "shared water should keep time-of-day tint")
  assert.ok(waterStageCss.includes(".stillWaterPlane"), "shared water should keep the still-water plane")
  assert.ok(waterStageCss.includes(".deepLayer"), "shared water should deepen during the dive transition")
  assert.ok(waterStageCss.includes(".vignetteLayer"), "shared water should keep the page-level vignette")
  assert.ok(waterStageCss.includes("animation: stillWaterBreath 16s"), "the shared still water should breathe slowly")
  assert.equal(stillHeroCss.includes(".waterCanvas"), false, "hero CSS should not keep its own water canvas")
  assert.ok(stillHeroCss.includes("white-space: nowrap"), "hero title lines should not split the maxim mid-phrase")
  assert.equal(stillHeroCss.includes("--ripple-push-x"), false, "hero title should not be pushed by ripples")
  assert.equal(stillHeroCss.includes("--ripple-title-blur"), false, "hero title should not blur when ripples pass")
  assert.ok(stillHeroCss.includes(".zhaoMark"), "hero should position the artistic 照 seal")
  assert.ok(topNav.includes("home-nav-zhao"), "top nav should use the same seal container language")
  assert.ok(topNav.includes("YangmingA1Mark"), "top nav seal should use the project brand art glyph")
  assert.ok(topNav.includes("window.scrollY"), "top nav should fade according to real page scroll")
  assert.ok(topNav.includes("viewportHeight * 0.5"), "top nav should fully hide after about half a viewport")
  assert.ok(topNav.includes("scrollFade > 0.08"), "top nav should disable pointer events once it has faded away")
  assert.ok(stillHeroCss.includes(".door"), "main entrance should be styled as a threshold")
  assert.ok(stillHeroCss.includes(".doorLine"), "main entrance should use a breathing fine line")
  assert.equal(stillHeroCss.includes("rounded-full border px-6"), false, "main entrance should not look like a pill CTA button")
  assert.ok(stillHeroCss.includes("@media (prefers-reduced-motion: reduce)"), "hero should respect reduced motion")

  assert.ok(gates.includes("知行心卷"), "gates should include the five destination doors")
  assert.ok(gates.includes("明镜止水"), "gates should include the five destination doors")
  assert.ok(gates.includes("一念心湖"), "gates should include the five destination doors")
  assert.ok(gates.includes("照见实盘"), "gates should include the five destination doors")
  assert.ok(gates.includes("档案馆"), "gates should include the five destination doors")
  assert.ok(gates.includes('href: "/zhixing-scroll"'), "知行心卷 gate should link to the scroll route")
  assert.ok(gates.includes('href: "/zhixing-still-water"'), "明镜止水 gate should link to the still-water route")
  assert.ok(gates.includes('href: "/one-thought-lake"'), "一念心湖 gate should link to the lake route")
  assert.ok(gates.includes('href: "/review"'), "照见实盘 gate should link to review")
  assert.ok(gates.includes('href: "/mirror-archive"'), "档案馆 gate should link to archive")
  assert.equal(gates.includes("canvasRef"), false, "Gate2 should not create a second water canvas")
  assert.equal(gates.includes("ripplesRef"), false, "Gate2 should not manage a separate ripple list")
  assert.equal(gates.includes("fixedRef"), false, "Gate2 should not pin its own background")
  assert.ok(gates.includes("home-water-ripple"), "Gate2 should ask the shared water to ripple when a gate is reached")
  assert.ok(gates.includes("getBoundingClientRect"), "Gate2 should use page scroll distance, not an isolated scroller")
  assert.ok(gates.includes("data-here"), "Gate2 current gate should be marked as the water recognizes arrival")
  assert.ok(gates.includes("scrollIntoView"), "Gate2 should keep the back-to-water affordance")
  assert.equal(gatesCss.includes(".fixedWater"), false, "Gate2 should not keep a local water field")
  assert.equal(gatesCss.includes(".waterCanvas"), false, "Gate2 should not render its own canvas")
  assert.ok(gatesCss.includes(".seal"), "Gate2 should keep the five gate seal marks")
  assert.ok(gatesCss.includes("background: transparent"), "Gate2 should float over the shared water")
  assert.equal(gatesCss.includes(".threshold"), false, "Gate2 should not keep the old visible gate line")
  assert.equal(gatesCss.includes(".path"), false, "Gate2 should not draw a central path line")
  assert.equal(gatesCss.includes("border-radius: 14px"), false, "gates section should not keep the demo rounded container")
  assert.equal(gatesCss.includes("instrument-pane"), false, "gates section should not use dashboard/card styling")

  ;["股票", "代码", "收益", "涨跌", "买入", "卖出", "BTC", "AAPL"].forEach((forbiddenMarketToken) => {
    assert.equal(stillHero.includes(forbiddenMarketToken), false, `hero should not include readable market info: ${forbiddenMarketToken}`)
  })

  ;["/one-thought-lake", "/review", "/mirror-archive"].forEach((href) => {
    assert.ok(topNav.includes(`href: "${href}"`), `home nav missing route: ${href}`)
  })
  assert.ok(topNav.includes('href="/reflect"'), "home nav start button should use /reflect")
  assert.match(reflectAlias, /redirect\("\/assessment-entry"\)/)
  assert.match(reviewAlias, /redirect\("\/trade-review"\)/)
  assert.match(lakeAlias, /redirect\("\/one-thought-lake"\)/)
})
