import type { LoopNode, LivingMirrorLoopNodeId } from "./reflectionLoopTypes"

export const livingMirrorLoopNodes: LoopNode[] = [
  {
    id: "enter_reflection",
    index: 1,
    title: "入照心",
    subtitle: "第一次照见交易中的自己",
    principle: "以交易照人心",
    outputObject: "assessment_id",
    route: "/assessment-entry",
  },
  {
    id: "mirror_manifestation",
    index: 2,
    title: "九镜显影",
    subtitle: "显出主副人格与高危一念",
    principle: "以交易照人心",
    outputObject: "persona_result_id",
    route: "/assessment-ritual",
  },
  {
    id: "mirror_report",
    index: 3,
    title: "心镜报告",
    subtitle: "生成风险雷达与七日处方",
    principle: "以交易照人心",
    outputObject: "mirror_report_id",
    route: "/assessment-result?preview=1",
  },
  {
    id: "daily_growth",
    index: 4,
    title: "今日修行",
    subtitle: "签到、观念、落印",
    principle: "以训练照变化",
    outputObject: "daily_growth_id",
    route: "/practice-change?preview=1",
  },
  {
    id: "trade_review",
    index: 5,
    title: "真实交易复盘",
    subtitle: "不复盘行情对错，只复盘谁在下单",
    principle: "以复盘照行为",
    outputObject: "trade_review_id",
    route: "/trade-review",
  },
  {
    id: "growth_profile",
    index: 6,
    title: "活镜成长谱",
    subtitle: "把每日心证连成变化图谱",
    principle: "以活镜照成长",
    outputObject: "growth_profile_id",
    route: "/mirror-scroll",
  },
  {
    id: "behavior_loop",
    index: 7,
    title: "循环之镜",
    subtitle: "照见触发、一念、行为、结果的重复循环",
    principle: "以复盘照行为",
    outputObject: "behavior_loop_id",
    route: "/cycle-mirror",
  },
  {
    id: "retest_change",
    index: 8,
    title: "复测变化",
    subtitle: "对比首测与复测，证明行为是否改变",
    principle: "以训练照变化",
    outputObject: "retest_id",
    route: "/practice-change?preview=1",
  },
  {
    id: "assistant_handoff",
    index: 9,
    title: "助教承接",
    subtitle: "把人格、风险、心证与下一步交给助教",
    principle: "以活镜照成长",
    outputObject: "assistant_handoff_id",
    route: "/admin",
  },
  {
    id: "share_global",
    index: 10,
    title: "分享 / 全球照见层",
    subtitle: "分享照见，匿名映照全球交易者的一念",
    principle: "以活镜照成长",
    outputObject: "global_reflection_id",
    route: "/global-reflection",
  },
  {
    id: "next_enter_reflection",
    index: 11,
    title: "下一次入照心",
    subtitle: "带着变化进入下一轮照见",
    principle: "以交易照人心",
    outputObject: "next_assessment_id",
    route: "/assessment-entry",
  },
]

export const livingMirrorLoopPrinciples = [
  "以交易照人心",
  "以复盘照行为",
  "以训练照变化",
  "以活镜照成长",
] as const

export const livingMirrorLoopSprintLabels: Record<LivingMirrorLoopNodeId, string> = {
  enter_reflection: "Sprint 8",
  mirror_manifestation: "Sprint 8",
  mirror_report: "Sprint 9",
  daily_growth: "Sprint 10",
  trade_review: "Sprint 10.5",
  growth_profile: "Sprint 10.8",
  behavior_loop: "Sprint 11.5",
  retest_change: "Sprint 10",
  assistant_handoff: "Sprint 12",
  share_global: "Sprint 13-14",
  next_enter_reflection: "Sprint 8+",
}
