import type { LoopNode, LivingMirrorLoopNodeId } from "./reflectionLoopTypes"

export const livingMirrorLoopNodes: LoopNode[] = [
  {
    id: "enter_reflection",
    index: 1,
    title: "入照心",
    subtitle: "第一次照见交易中的自己",
    principle: "以交易照人心",
    outputObject: "assessment_id",
    route: "/assessment-entry",
  },
  {
    id: "daily_thought",
    index: 2,
    title: "今日一念",
    subtitle: "从三十六场景里浮现当天最先带走你的那一念",
    principle: "以交易照人心",
    outputObject: "daily_thought_id",
    route: "/assessment",
  },
  {
    id: "reflection_back",
    index: 3,
    title: "照回",
    subtitle: "把这一念照回情绪、场景与反应",
    principle: "以交易照人心",
    outputObject: "reflection_back_id",
    route: "/assessment",
  },
  {
    id: "heart_thief",
    index: 4,
    title: "心贼显影",
    subtitle: "照见贪、急、惧、不甘等当日心贼",
    principle: "以交易照人心",
    outputObject: "heart_thief_id",
    route: "/assessment",
  },
  {
    id: "mirror_manifestation",
    index: 5,
    title: "九镜显影",
    subtitle: "把心贼归入今日主镜与副镜",
    principle: "以交易照人心",
    outputObject: "persona_result_id",
    route: "/assessment-ritual",
  },
  {
    id: "heart_proof",
    index: 6,
    title: "今日心证",
    subtitle: "沉淀一句“我看见……”",
    principle: "以训练照变化",
    outputObject: "heart_proof_id",
    route: "/assessment",
  },
  {
    id: "daily_practice",
    index: 7,
    title: "今日修行",
    subtitle: "把心证落成一个可执行动作",
    principle: "以训练照变化",
    outputObject: "daily_growth_id",
    route: "/practice-change?preview=1",
  },
  {
    id: "conscience_seal",
    index: 8,
    title: "致良知落印",
    subtitle: "把今日心证与修行动作落印为证",
    principle: "以训练照变化",
    outputObject: "daily_seal_id",
    route: "/assessment",
  },
  {
    id: "mirror_report",
    index: 9,
    title: "今日照见总结",
    subtitle: "生成当天心镜报告",
    principle: "以训练照变化",
    outputObject: "mirror_report_id",
    route: "/assessment-result",
  },
  {
    id: "trade_review",
    index: 10,
    title: "真实交易复盘",
    subtitle: "拍照持仓，结合历史 K 线回看交易场景与临场反应",
    principle: "以复盘照行为",
    outputObject: "trade_review_id",
    route: "/trade-review",
  },
  {
    id: "mirror_archive",
    index: 11,
    title: "心镜档案",
    subtitle: "报告、心证、修行、复盘、复测，全部归档",
    principle: "以活镜照成长",
    outputObject: "mirror_archive_id",
    route: "/mirror-archive",
  },
  {
    id: "mirror_scroll",
    index: 12,
    title: "心镜长卷",
    subtitle: "把每日证据连成成长叙事",
    principle: "以活镜照成长",
    outputObject: "mirror_scroll_id",
    route: "/mirror-scroll",
  },
  {
    id: "retest_change",
    index: 13,
    title: "复测变化",
    subtitle: "对比首测与复测，证明行为是否改变",
    principle: "以训练照变化",
    outputObject: "retest_id",
    route: "/practice-change?preview=1",
  },
  {
    id: "next_enter_reflection",
    index: 14,
    title: "下一次入照心",
    subtitle: "带着变化进入下一轮照见",
    principle: "以交易照人心",
    outputObject: "next_assessment_id",
    route: "/assessment-entry",
  },
]

export const livingMirrorLoopPrinciples = [
  "以交易照人心",
  "以复盘照行为",
  "以训练照变化",
  "以活镜照成长",
] as const

export const livingMirrorLoopSprintLabels: Record<LivingMirrorLoopNodeId, string> = {
  enter_reflection: "Sprint 8",
  daily_thought: "Sprint 10",
  reflection_back: "Sprint 10",
  heart_thief: "Sprint 10",
  mirror_manifestation: "Sprint 8",
  heart_proof: "Sprint 10.8",
  daily_practice: "Sprint 10.8",
  conscience_seal: "Sprint 10.8",
  trade_review: "Sprint 10.5",
  mirror_report: "Sprint 9",
  mirror_archive: "Sprint 11",
  mirror_scroll: "Sprint 11.5",
  retest_change: "Sprint 10",
  next_enter_reflection: "Sprint 8+",
}
