const assert = require("node:assert")
const { existsSync, readFileSync, readdirSync, statSync } = require("node:fs")
const { join } = require("node:path")

const root = process.cwd()

function collectFiles(dir) {
  return readdirSync(dir).flatMap((name) => {
    const file = join(dir, name)
    return statSync(file).isDirectory() ? collectFiles(file) : file
  })
}

const zhaoLogoPath = join(root, "miniprogram", "assets", "brand", "ymty-zhao-logo.svg")
const allPageWxml = collectFiles(join(root, "miniprogram", "pages"))
  .filter((file) => file.endsWith(".wxml"))
  .map((file) => readFileSync(file, "utf8"))
  .join("\n")
const appWxss = readFileSync(join(root, "miniprogram", "app.wxss"), "utf8")
const homeWxml = readFileSync(join(root, "miniprogram", "pages", "home", "index.wxml"), "utf8")
const reportWxml = readFileSync(join(root, "miniprogram", "pages", "report", "index.wxml"), "utf8")
const trainingWxml = readFileSync(join(root, "miniprogram", "pages", "training", "index.wxml"), "utf8")
const tradeReviewWxml = readFileSync(join(root, "miniprogram", "pages", "trade-review", "index.wxml"), "utf8")
const tradeReviewDetailWxml = readFileSync(join(root, "miniprogram", "pages", "trade-review-detail", "index.wxml"), "utf8")
const shareCardWxml = readFileSync(join(root, "miniprogram", "pages", "share-card", "index.wxml"), "utf8")
const mindWxml = readFileSync(join(root, "miniprogram", "pages", "mind", "index.wxml"), "utf8")
const homeWxss = readFileSync(join(root, "miniprogram", "pages", "home", "index.wxss"), "utf8")
const reportWxss = readFileSync(join(root, "miniprogram", "pages", "report", "index.wxss"), "utf8")
const trainingWxss = readFileSync(join(root, "miniprogram", "pages", "training", "index.wxss"), "utf8")
const shareCardWxss = readFileSync(join(root, "miniprogram", "pages", "share-card", "index.wxss"), "utf8")
const mindWxss = readFileSync(join(root, "miniprogram", "pages", "mind", "index.wxss"), "utf8")
assert.ok(existsSync(zhaoLogoPath), "zhao logo asset should exist")
const zhaoLogoSvg = readFileSync(zhaoLogoPath, "utf8")

assert.ok(homeWxml.includes('src="/assets/brand/ymty-zhao-logo.svg"'), "home brand avatar should use the art zhao logo asset")
assert.ok(homeWxml.includes('aria-label="阳明照见艺术标"'), "home art logo should have replacement text")
assert.ok(homeWxml.includes('class="brand-seal-frame"'), "home art logo should sit inside a restrained logo frame")
assert.ok(homeWxss.includes(".brand-seal-frame"), "home art logo frame should be styled")
assert.ok(homeWxss.includes("border: 1.5rpx solid rgba(224, 196, 136, 0.42)"), "home art logo frame should use a restrained gold border")
assert.ok(homeWxss.includes(".brand-seal-art"), "home art logo should be styled without the old seal background")
assert.ok(appWxss.includes(".brand-seal-frame"), "home art logo frame should be available as a global brand class")
assert.ok(appWxss.includes(".brand-seal-art"), "home art logo image should be available as a global brand class")
assert.ok(zhaoLogoSvg.includes("<svg"), "zhao logo asset should be SVG")
assert.ok(zhaoLogoSvg.includes('fill="none"'), "zhao logo asset should be line art")
assert.equal(/<rect|background/i.test(zhaoLogoSvg), false, "zhao logo asset should not include a background block")
assert.ok(reportWxml.includes('class="report-brand-mark brand-seal-frame"'), "report page brand mark should use the home art logo frame")
assert.ok(reportWxml.includes('src="/assets/brand/ymty-zhao-logo.svg"'), "report page brand mark should use the home art logo asset")
assert.ok(trainingWxml.includes('class="training-brand-mark brand-seal-frame"'), "training page brand mark should use the home art logo frame")
assert.ok(trainingWxml.includes('src="/assets/brand/ymty-zhao-logo.svg"'), "training page brand mark should use the home art logo asset")
assert.ok(shareCardWxml.includes('class="mini-seal brand-seal-frame"'), "share card preview brand mark should use the home art logo frame")
assert.ok(shareCardWxml.includes('class="poster-brand-seal brand-seal-frame"'), "share card poster brand mark should use the home art logo frame")
assert.ok(mindWxml.includes('class="seal brand-seal-frame"'), "mind page header brand mark should use the home art logo frame")
assert.ok(trainingWxml.includes('class="mind-seal brand-seal-frame"'), "training mind bridge should use the home art logo frame")
assert.ok(homeWxml.includes('class="living-written-mark brand-seal-frame"'), "home completion seal should use the home art logo frame")
assert.ok(homeWxml.includes('class="completion-living-mark brand-seal-frame"'), "home living mirror completion mark should use the home art logo frame")
assert.ok(homeWxml.includes('class="seal-mark-large brand-seal-frame"'), "home daily imprint seal should use the home art logo frame")
assert.equal(allPageWxml.includes("brand-zhao-mini"), false, "pages must not render the old CSS geometry logo")
assert.equal(allPageWxml.includes("zhao-eye"), false, "pages must not render hand-built logo geometry")
assert.equal(homeWxml.includes('aria-label="阳明照见 C16 小标"'), false, "home top brand should not keep the old C16 mini mark")
assert.ok(reportWxml.includes('aria-label="阳明照见艺术标"'), "report art logo should have replacement text")
assert.ok(trainingWxml.includes('aria-label="阳明照见艺术标"'), "training art logo should have replacement text")
assert.ok(trainingWxml.includes('aria-label="阳明照见艺术标"'), "training mind bridge mark should use the shared art logo replacement text")
assert.ok(shareCardWxml.includes('aria-label="阳明照见艺术标"'), "share card art logo should have replacement text")
assert.ok(mindWxml.includes('aria-label="阳明照见艺术标"'), "mind art logo should have replacement text")
assert.ok(homeWxml.includes('class="living-written-mark brand-seal-frame"'), "home completion mark should use the shared art logo replacement text")
assert.ok(homeWxml.includes('class="seal-mark-large brand-seal-frame"'), "home daily imprint mark should use the shared art logo replacement text")
assert.ok(tradeReviewWxml.includes('aria-label="交易复盘截图预览"'), "trade review screenshot preview should have replacement text")
assert.ok(tradeReviewDetailWxml.includes('aria-label="交易复盘截图详情"'), "trade review screenshot detail should have replacement text")
assert.ok(reportWxss.includes(".report-brand-row"), "report brand header should be styled")
assert.ok(trainingWxss.includes(".training-brand-row"), "training brand header should be styled")
assert.ok(trainingWxss.includes(".mini-glyph-train"), "training page should include UI glyph geometry")
assert.equal(reportWxml.includes("report-brand-mark brand-zhao-mini"), false, "report page brand mark must not use the old C16 mini mark")
assert.equal(trainingWxml.includes("training-brand-mark brand-zhao-mini"), false, "training page brand mark must not use the old C16 mini mark")
assert.equal(shareCardWxml.includes("mini-seal brand-zhao-mini"), false, "share card preview brand mark must not use the old C16 mini mark")
assert.equal(shareCardWxml.includes("poster-brand-seal brand-zhao-mini"), false, "share card poster brand mark must not use the old C16 mini mark")
assert.equal(mindWxml.includes("seal brand-zhao-mini"), false, "mind page header brand mark must not use the old C16 mini mark")
assert.ok(homeWxss.includes(".living-written-mark"), "home completion seal should not rely on font text")
assert.equal(homeWxml.includes('<view class="brand-seal">知</view>'), false, "home must not render font-based zhi logo")
assert.equal(shareCardWxml.includes('<view class="mini-seal">知</view>'), false, "share card preview must not render font-based zhi logo")
assert.equal(shareCardWxml.includes('<view class="poster-brand-seal">知</view>'), false, "share card poster must not render font-based zhi logo")
assert.equal(trainingWxml.includes("{{mind ? mind.glyph : '照'}}"), false, "training must not render font-based zhao logo")
assert.equal(mindWxml.includes('<view class="seal">照</view>'), false, "mind page must not render a font-based zhao logo")
assert.equal(homeWxml.includes('<text>照</text>'), false, "home completion seal must not render a font-based zhao logo")
assert.equal(homeWxml.includes('<view class="seal-mark-large">照</view>'), false, "home daily imprint seal must not render a font-based zhao logo")

console.log("Mini program brand asset guard passed.")
