const assert = require("node:assert")
const { readFileSync } = require("node:fs")
const { join } = require("node:path")

const root = process.cwd()

const appWxss = readFileSync(join(root, "miniprogram", "app.wxss"), "utf8")
const homeWxml = readFileSync(join(root, "miniprogram", "pages", "home", "index.wxml"), "utf8")
const reportWxml = readFileSync(join(root, "miniprogram", "pages", "report", "index.wxml"), "utf8")
const trainingWxml = readFileSync(join(root, "miniprogram", "pages", "training", "index.wxml"), "utf8")
const tradeReviewWxml = readFileSync(join(root, "miniprogram", "pages", "trade-review", "index.wxml"), "utf8")
const tradeReviewDetailWxml = readFileSync(join(root, "miniprogram", "pages", "trade-review-detail", "index.wxml"), "utf8")
const shareCardWxml = readFileSync(join(root, "miniprogram", "pages", "share-card", "index.wxml"), "utf8")
const mindWxml = readFileSync(join(root, "miniprogram", "pages", "mind", "index.wxml"), "utf8")
const homeWxss = readFileSync(join(root, "miniprogram", "pages", "home", "index.wxss"), "utf8")
const reportWxss = readFileSync(join(root, "miniprogram", "pages", "report", "index.wxss"), "utf8")
const trainingWxss = readFileSync(join(root, "miniprogram", "pages", "training", "index.wxss"), "utf8")
const shareCardWxss = readFileSync(join(root, "miniprogram", "pages", "share-card", "index.wxss"), "utf8")
const mindWxss = readFileSync(join(root, "miniprogram", "pages", "mind", "index.wxss"), "utf8")

assert.ok(appWxss.includes(".brand-zhao-mini"), "global mini mark class should exist")
assert.ok(appWxss.includes(".zhao-eye"), "mini mark should be built from CSS geometry")
assert.ok(homeWxml.includes("brand-seal brand-zhao-mini"), "home avatar should use C16 mini mark")
assert.ok(reportWxml.includes("report-brand-mark brand-zhao-mini"), "report page should use C16 mini mark")
assert.ok(trainingWxml.includes("training-brand-mark brand-zhao-mini"), "training page should use C16 mini mark")
assert.ok(trainingWxml.includes("mind-seal brand-zhao-mini"), "training mind bridge should use CSS C16 mark")
assert.ok(shareCardWxml.includes("mini-seal brand-zhao-mini"), "share card preview should use CSS C16 mark")
assert.ok(shareCardWxml.includes("poster-brand-seal brand-zhao-mini"), "share card poster should use CSS C16 mark")
assert.ok(mindWxml.includes("seal brand-zhao-mini"), "mind page header seal should use CSS C16 mark")
assert.ok(homeWxml.includes("living-written-mark brand-zhao-mini"), "home completion seal should use CSS C16 mark")
assert.ok(homeWxml.includes("seal-mark-large brand-zhao-mini"), "home daily imprint seal should use CSS C16 mark")
assert.ok(homeWxml.includes('aria-label="阳明照见 C16 小标"'), "home C16 mini mark should have replacement text")
assert.ok(reportWxml.includes('aria-label="阳明照见报告小标"'), "report C16 mini mark should have replacement text")
assert.ok(trainingWxml.includes('aria-label="阳明照见训练小标"'), "training C16 mini mark should have replacement text")
assert.ok(trainingWxml.includes('aria-label="开盘照心小标"'), "training mind bridge mark should have replacement text")
assert.ok(shareCardWxml.includes('aria-label="阳明照见分享卡小标"'), "share card mini mark should have replacement text")
assert.ok(shareCardWxml.includes('aria-label="阳明照见分享卡海报小标"'), "share card poster mark should have replacement text")
assert.ok(mindWxml.includes('aria-label="阳明照见开盘照心小标"'), "mind C16 mini mark should have replacement text")
assert.ok(homeWxml.includes('aria-label="今日已照见小标"'), "home completion C16 mini mark should have replacement text")
assert.ok(homeWxml.includes('aria-label="今日之印小标"'), "home daily imprint C16 mini mark should have replacement text")
assert.ok(tradeReviewWxml.includes('aria-label="交易复盘截图预览"'), "trade review screenshot preview should have replacement text")
assert.ok(tradeReviewDetailWxml.includes('aria-label="交易复盘截图详情"'), "trade review screenshot detail should have replacement text")
assert.ok(homeWxss.includes(".brand-seal.brand-zhao-mini"), "home seal should disable font text sizing")
assert.ok(reportWxss.includes(".report-brand-row"), "report brand header should be styled")
assert.ok(trainingWxss.includes(".training-brand-row"), "training brand header should be styled")
assert.ok(trainingWxss.includes(".mini-glyph-train"), "training page should include UI glyph geometry")
assert.ok(shareCardWxss.includes(".mini-seal.brand-zhao-mini"), "share card mini mark should use tuned geometry")
assert.ok(shareCardWxss.includes(".poster-brand-seal.brand-zhao-mini"), "share card poster mark should use tuned geometry")
assert.ok(mindWxss.includes(".seal.brand-zhao-mini"), "mind page seal should tune C16 geometry")
assert.ok(homeWxss.includes(".living-written-mark"), "home completion seal should not rely on font text")
assert.ok(homeWxss.includes(".seal-mark-large .zhao-eye"), "home daily imprint seal should tune C16 geometry")
assert.equal(homeWxml.includes('<view class="brand-seal">知</view>'), false, "home must not render font-based zhi logo")
assert.equal(shareCardWxml.includes('<view class="mini-seal">知</view>'), false, "share card preview must not render font-based zhi logo")
assert.equal(shareCardWxml.includes('<view class="poster-brand-seal">知</view>'), false, "share card poster must not render font-based zhi logo")
assert.equal(trainingWxml.includes("{{mind ? mind.glyph : '照'}}"), false, "training must not render font-based zhao logo")
assert.equal(mindWxml.includes('<view class="seal">照</view>'), false, "mind page must not render a font-based zhao logo")
assert.equal(homeWxml.includes('<text>照</text>'), false, "home completion seal must not render a font-based zhao logo")
assert.equal(homeWxml.includes('<view class="seal-mark-large">照</view>'), false, "home daily imprint seal must not render a font-based zhao logo")

console.log("Mini program brand asset guard passed.")
