const assert = require("node:assert")
const { readFileSync } = require("node:fs")
const { join } = require("node:path")

const root = process.cwd()
const homeJs = readFileSync(join(root, "miniprogram", "pages", "home", "index.js"), "utf8")
const homeWxml = readFileSync(join(root, "miniprogram", "pages", "home", "index.wxml"), "utf8")
const homeWxss = readFileSync(join(root, "miniprogram", "pages", "home", "index.wxss"), "utf8")

assert.ok(homeWxml.includes('class="home-continuity-panel"'), "home should render a below-fold continuity panel")
assert.ok(homeWxml.includes("homeContinuitySteps.length"), "continuity panel should render only the compact home continuity slice")
assert.ok(homeWxml.includes('wx:for="{{homeContinuitySteps}}"'), "continuity panel should loop over at most three home continuity steps")
assert.equal(homeWxml.includes("index < 3 || item.current"), false, "continuity panel should not leak extra steps when the current step is late")
assert.ok(homeWxml.includes("closureEvidenceChain.progressPercent"), "continuity panel should still use the shared closure evidence chain progress")
assert.ok(homeWxml.includes("closureEvidenceChain.nextActionText"), "continuity panel should carry the next action")
assert.ok(homeWxml.indexOf('class="mini-mirror-card"') < homeWxml.indexOf('class="edict-scroll"'), "daily proof and primary action should lead the home flow")
assert.ok(homeWxml.indexOf('class="home-focus-card"') < homeWxml.indexOf('class="home-continuity-panel"'), "current action should come before the continuity panel")
assert.ok(homeWxml.includes('class="home-narrative-panel"'), "home should render a second-act narrative panel after the primary action")
assert.ok(homeWxml.indexOf('class="home-focus-card"') < homeWxml.indexOf('class="home-narrative-panel"'), "home second act should come after the primary action")
assert.ok(homeWxml.includes('class="home-scene-bridge"'), "home should bridge the primary action into the second-act narrative")
assert.ok(homeWxml.indexOf('class="home-focus-card"') < homeWxml.indexOf('class="home-scene-bridge"'), "home scene bridge should come after the primary action")
assert.ok(homeWxml.indexOf('class="home-scene-bridge"') < homeWxml.indexOf('class="home-narrative-panel"'), "home scene bridge should lead into the second act")
;["下一幕", "这一条真实记录，会继续生成活镜、心证卡和档案证据。"].forEach((label) => {
  assert.ok(homeWxml.includes(label), `home scene bridge should include ${label}`)
})
assert.ok(homeWxml.indexOf('class="home-narrative-panel"') < homeWxml.indexOf('class="home-continuity-panel"'), "home second act should explain the loop before the evidence panel")
;["留下真实记录", "看见第一念", "写入活镜", "生成心证卡", "进入档案", "明日继续"].forEach((label) => {
  assert.ok(homeWxml.includes(label), `home second act should include ${label}`)
})
;["第一幕", "第二幕", "第三幕", "第四幕", "第五幕", "第六幕"].forEach((label) => {
  assert.ok(homeWxml.includes(label), `home second act should read like staged progression with ${label}`)
})
assert.ok(homeWxml.includes('class="home-narrative-artifact"'), "home second act should make each generated result feel tangible")
assert.ok(homeWxml.includes('class="home-evidence-showcase"'), "home second act should show the generated evidence artifacts")
;["活镜点亮", "心证卡落印", "档案归卷"].forEach((label) => {
  assert.ok(homeWxml.includes(label), `home evidence showcase should include ${label}`)
})
;["待点亮", "待落印", "待归卷"].forEach((label) => {
  assert.ok(homeWxml.includes(label), `home evidence showcase should show unfinished state ${label}`)
})
assert.ok(homeWxml.includes("待开卷"), "home unfinished evidence state should feel like a waiting scroll")
assert.ok(homeWxml.includes('class="home-completion-seal-roll"'), "home completed state should render a sealed evidence roll")
;["今日封卷", "活镜已点亮", "心证已落印", "档案已归卷"].forEach((label) => {
  assert.ok(homeWxml.includes(label), `home completed state should include ${label}`)
})
assert.ok(homeWxml.includes('class="home-completion-exit"'), "home completed state should collect final actions in a sealing exit")
;["封卷出口", "进入档案", "明日继续"].forEach((label) => {
  assert.ok(homeWxml.includes(label), `home completion exit should include ${label}`)
})
assert.ok(homeWxml.includes('class="home-completion-share-node"'), "home completed state should expose shareable evidence nodes")
;["传播节点", "心证卡海报", "活镜回看", "档案证据"].forEach((label) => {
  assert.ok(homeWxml.includes(label), `home share node should include ${label}`)
})
assert.ok(homeWxml.includes('data-type="daily_mantra"'), "home share node should reuse the daily heart proof share-card route")
assert.ok(homeWxml.includes('class="home-today-state-card"'), "home should render a quiet server today-state card")
assert.ok(homeWxml.includes("今日所照"), "today-state card should use reader-facing copy")
assert.ok(homeWxml.includes("serverTodayStateView.statusText"), "today-state card should consume normalized status text")
assert.ok(homeWxml.includes("serverTodayStateView.nextActionText"), "today-state card should consume normalized next action")
assert.ok(homeWxml.includes("serverTodayStateView.progress"), "today-state card should consume normalized progress")
assert.ok(homeWxml.includes('bindtap="goServerTodayAction"'), "today-state card should route through an explicit action handler")
assert.equal(homeWxml.includes('class="kline-mind-entry"'), false, "home should not keep a secondary k-line practice card in the daily narrative")
assert.equal(homeWxml.includes('bindtap="goKlineMind"'), false, "home should not route directly into k-line practice")
assert.ok(homeWxml.includes('class="home-bottom-echo"'), "home should fill the pre-tabbar area with a quiet closing strip")
assert.ok(homeWxml.indexOf('class="home-bottom-echo"') < homeWxml.indexOf("<compliance-notice"), "closing strip should sit above the compliance notice")
assert.ok(homeWxss.includes(".home-continuity-panel"), "continuity panel should be styled")
assert.ok(homeWxss.includes(".home-scene-bridge"), "home scene bridge should be styled")
assert.ok(homeWxss.includes(".home-narrative-panel"), "home second-act narrative panel should be styled")
assert.ok(homeWxss.includes(".home-evidence-showcase"), "home generated evidence showcase should be styled")
assert.ok(homeWxss.includes(".home-completion-seal-roll"), "home completed evidence roll should be styled")
assert.ok(homeWxss.includes(".home-completion-exit"), "home completed exit should be styled")
assert.ok(homeWxss.includes(".home-completion-share-node"), "home completed share node should be styled")
assert.ok(homeWxss.includes(".home-today-state-card"), "today-state card should be styled")
assert.ok(homeWxss.includes(".home-bottom-echo"), "closing strip should be styled")
assert.ok(homeJs.includes("fetchTodayState"), "home should read server TodayState through the API client")
assert.ok(homeJs.includes("buildHomeTodayStateView"), "home should normalize TodayState before rendering")
assert.ok(homeJs.includes("resolveHomeTodayStateAction"), "home should map TodayState nextAction through known routes")
assert.ok(homeJs.includes("serverTodayStateView"), "home should keep TodayState in a dedicated view model")
assert.ok(homeJs.includes("serverTodayStateAction"), "home should keep resolved TodayState action separately")
assert.ok(homeJs.includes("goServerTodayAction"), "home should expose a TodayState action handler")
assert.equal(homeWxss.includes(".kline-mind-entry"), false, "home should not keep dead k-line entry styles after removing the secondary entrance")
assert.equal(homeWxss.includes("calc(240rpx + env(safe-area-inset-bottom))"), false, "home shell should not keep the old oversized tabbar spacer")
assert.equal(homeWxss.includes("calc(180rpx + env(safe-area-inset-bottom))"), false, "home content should not keep the old oversized inner spacer")
assert.equal(homeWxss.includes("calc(160rpx + env(safe-area-inset-bottom))"), false, "home hero should not keep the old oversized bottom padding")
assert.equal(homeWxss.includes("calc(148rpx + env(safe-area-inset-bottom))"), false, "mobile hero should not keep the old oversized bottom padding")
assert.equal(homeWxss.includes("calc(140rpx + env(safe-area-inset-bottom))"), false, "narrow mobile hero should not keep the old oversized bottom padding")

console.log("Mini program home scroll continuity guard passed.")
