const assert = require("node:assert")
const { readFileSync } = require("node:fs")
const { join } = require("node:path")

const root = process.cwd()
const homeWxml = readFileSync(join(root, "miniprogram", "pages", "home", "index.wxml"), "utf8")
const homeWxss = readFileSync(join(root, "miniprogram", "pages", "home", "index.wxss"), "utf8")

assert.ok(homeWxml.includes('class="home-continuity-panel"'), "home should render a below-fold continuity panel")
assert.ok(homeWxml.includes("homeContinuitySteps.length"), "continuity panel should render only the compact home continuity slice")
assert.ok(homeWxml.includes('wx:for="{{homeContinuitySteps}}"'), "continuity panel should loop over at most three home continuity steps")
assert.equal(homeWxml.includes("index < 3 || item.current"), false, "continuity panel should not leak extra steps when the current step is late")
assert.ok(homeWxml.includes("closureEvidenceChain.progressPercent"), "continuity panel should still use the shared closure evidence chain progress")
assert.ok(homeWxml.includes("closureEvidenceChain.nextActionText"), "continuity panel should carry the next action")
assert.ok(homeWxml.indexOf('class="mini-mirror-card"') < homeWxml.indexOf('class="edict-scroll"'), "daily proof and primary action should lead the home flow")
assert.ok(homeWxml.indexOf('class="home-focus-card"') < homeWxml.indexOf('class="home-continuity-panel"'), "current action should come before the continuity panel")
assert.ok(homeWxml.indexOf('class="home-continuity-panel"') < homeWxml.indexOf('class="kline-mind-entry"'), "secondary k-line practice should come after the continuity panel")
assert.ok(homeWxml.indexOf('class="three-seals-block"') < homeWxml.indexOf('class="kline-mind-entry"'), "secondary k-line practice should not interrupt the active daily action block")
assert.ok(homeWxml.includes('class="home-bottom-echo"'), "home should fill the pre-tabbar area with a quiet closing strip")
assert.ok(homeWxml.indexOf('class="home-bottom-echo"') < homeWxml.indexOf("<compliance-notice"), "closing strip should sit above the compliance notice")
assert.ok(homeWxss.includes(".home-continuity-panel"), "continuity panel should be styled")
assert.ok(homeWxss.includes(".home-bottom-echo"), "closing strip should be styled")
assert.ok(homeWxss.includes("border: 1rpx solid rgba(217, 189, 122, 0.08)"), "k-line entry should read as a restrained secondary entrance")
assert.equal(homeWxss.includes("calc(240rpx + env(safe-area-inset-bottom))"), false, "home shell should not keep the old oversized tabbar spacer")
assert.equal(homeWxss.includes("calc(180rpx + env(safe-area-inset-bottom))"), false, "home content should not keep the old oversized inner spacer")
assert.equal(homeWxss.includes("calc(160rpx + env(safe-area-inset-bottom))"), false, "home hero should not keep the old oversized bottom padding")
assert.equal(homeWxss.includes("calc(148rpx + env(safe-area-inset-bottom))"), false, "mobile hero should not keep the old oversized bottom padding")
assert.equal(homeWxss.includes("calc(140rpx + env(safe-area-inset-bottom))"), false, "narrow mobile hero should not keep the old oversized bottom padding")

console.log("Mini program home scroll continuity guard passed.")
